name: www.trashtruckauctions.com
favicon: null
layout_spectrum: 0.7543415080290288
typography_spectrum: 0.735928020440042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7754946087952703
  lightness: 0.146124548278749
  saturation: 0.7238485892303288
  rhythmicContrast: 0.9914273242466152
purpose: []
